# Generated by Django 5.1.1 on 2024-09-29 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_appointment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
